--------------------------
-- To generate DDLs. Set these properties in application.properties
--
-- spring.jpa.generate-ddl=true
-- spring.jpa.hibernate.ddl-auto=create
--
-- Hibernate will generate/run DDL and and print it in logs.
-- We can use it these DDL, DML in flyaway migrate script
-- which will initialize DB on startup.
-- After that change ddl-auto=create to ddl-auto=update
--
--------------------------

drop table if exists item;
drop table if exists address;
drop table if exists customer;
drop table if exists customer_order_items;
drop table if exists customer_order;

create table address (id integer generated by default as identity, city varchar(255), state varchar(255), street varchar(255), zip varchar(255), primary key (id));
create table customer (id integer generated by default as identity, name varchar(255), address_id integer, primary key (id));
create table customer_order_items (customer_order_id integer not null, items_id integer not null);
create table customer_order (id integer generated by default as identity, customer_id integer, primary key (id));
create table item (id integer generated by default as identity, name varchar(255), price double, primary key (id));

alter table customer add constraint fk_customer_address foreign key (address_id) references address;
alter table customer_order_items add constraint fk_customer_order_items_item foreign key (items_id) references item;
alter table customer_order_items add constraint fk_customer_order_items_customer_order foreign key (customer_order_id) references customer_order;
alter table customer_order add constraint fk_customer_order_customer foreign key (customer_id) references customer;
