# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'trash_kick' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
end
