package com.sc.spring3.domain;

// Generated Dec 11, 2011 2:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS")
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "id_sequence", sequenceName = "id_sequence", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_sequence")
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@Column(name = "STREET", length = 250)
	private String street;

	@Column(name = "CITY", length = 250)
	private String city;

	@Column(name = "ZIP", length = 10)
	private String zip;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "address")
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Address() {
	}

	public Address(Long id) {
		this.id = id;
	}

	public Address(Long id, String street, String city, String zip,
			Set<Customer> customers) {
		this.id = id;
		this.street = street;
		this.city = city;
		this.zip = zip;
		this.customers = customers;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@XmlTransient
	public Set<Customer> getCustomers() {
		return customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}
}
