package com.sc.spring3.domain;

// Generated Dec 11, 2011 2:35:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@NamedQueries(value = { @NamedQuery(name = "allCustomers", query = "select c from Customer c") })
@Entity
@Table(name = "CUSTOMER")
public class Customer extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "id_sequence", sequenceName = "id_sequence", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_sequence")
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	@JoinColumn(name = "LOCATION", insertable=true, updatable=true)
	private Address address;

	@Column(name = "NAME", nullable = false, length = 250)
	private String name;

	@Column(name = "EMAIL", length = 250)
	private String email;

	@Column(name = "SALARY", precision = 0, scale = 0)
	private Double salary;

	public Customer() {
	}

	public Customer(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Customer(Long id, Address address, String name, String email, Double salary) {
		this.id = id;
		this.address = address;
		this.name = name;
		this.email = email;
		this.salary = salary;
	}

	@Override
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}
}
