INSERT INTO SC_USER(ID, USER_NAME, USER_PASSWORD)
VALUES (100, 'sheraz', '{noop}password');

INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1000, 'READ');

INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1100, 'ROLE_USER');

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2000, 100, 1000);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2100, 100, 1100);
