spring.application.name=todo

app.db.path=./data/todo.db
spring.datasource.url=jdbc:sqlite:${app.db.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.datasource.hikari.maximum-pool-size=1
