apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::691884051469:user/eks-user
      username: eks-user
      groups:
        - system:masters