package com.sc.spring3.domain;

// Generated Dec 11, 2011 2:35:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS", schema = "PUBLIC")
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String street;
	private String city;
	private String zip;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Address() {
	}

	public Address(Long id) {
		this.id = id;
	}

	public Address(Long id, String street, String city, String zip, Set<Customer> customers) {
		this.id = id;
		this.street = street;
		this.city = city;
		this.zip = zip;
		this.customers = customers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "STREET", length = 250)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", length = 250)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP", length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Customer> getCustomerses() {
		return this.customers;
	}

	public void setCustomerses(Set<Customer> userses) {
		this.customers = userses;
	}

}
