#!/bin/bash

# Mapping of kebab-case to lowerCamelCase class names
declare -A conversions=(
    ["app-container"]="appContainer"
    ["sidebar-header"]="sidebarHeader"
    ["nav-menu"]="navMenu"
    ["nav-item"]="navItem"
    ["nav-link"]="navLink"
    ["main-content"]="mainContent"
    ["login-container"]="loginContainer"
    ["form-group"]="formGroup"
    ["form-actions"]="formActions"
    ["dashboard-grid"]="dashboardGrid"
    ["clinic-day-details"]="clinicDayDetails"
    ["details-grid"]="detailsGrid"
    ["detail-section"]="detailSection"
    ["detail-section-title"]="detailSectionTitle"
    ["header-actions"]="headerActions"
    ["table-container"]="tableContainer"
    ["table-scroll"]="tableScroll"
    ["card-stat"]="cardStat"
    ["card-stat-label"]="cardStatLabel"
    ["card-stat-value"]="cardStatValue"
    ["person-list"]="personList"
    ["person-item"]="personItem"
    ["person-name"]="personName"
    ["person-remove-btn"]="personRemoveBtn"
    ["person-role"]="personRole"
    ["search-input"]="searchInput"
    ["search-dropdown"]="searchDropdown"
    ["search-dropdown-item"]="searchDropdownItem"
    ["dropdown-item-info"]="dropdownItemInfo"
    ["dropdown-item-name"]="dropdownItemName"
    ["dropdown-item-role"]="dropdownItemRole"
    ["dropdown-item-add-btn"]="dropdownItemAddBtn"
    ["search-wrapper"]="searchWrapper"
    ["search-input-container"]="searchInputContainer"
    ["dropdown-toggle-btn"]="dropdownToggleBtn"
    ["no-assignments"]="noAssignments"
    ["super-admin-only"]="superAdminOnly"
    ["org-selector"]="orgSelector"
    ["color-preview"]="colorPreview"
    ["color-value"]="colorValue"
    ["flex-row-15"]="flexRow15"
    ["flex-column"]="flexColumn"
    ["hamburger-btn"]="hamburgerBtn"
    ["hamburger-icon"]="hamburgerIcon"
    ["sidebar-overlay"]="sidebarOverlay"
    ["checkbox-label"]="checkboxLabel"
    ["checkbox-box"]="checkboxBox"
    ["radio-label"]="radioLabel"
    ["radio-box"]="radioBox"
    ["input-group"]="inputGroup"
    ["modal-actions"]="modalActions"
    ["modal-header"]="modalHeader"
    ["modal-content"]="modalContent"
    ["close-btn"]="closeBtn"
    ["list-item"]="listItem"
    ["list-item-name"]="listItemName"
    ["scrollable-list"]="scrollableList"
    ["count-badge"]="countBadge"
    ["action-btn"]="actionBtn"
    ["action-btn-edit"]="actionBtnEdit"
    ["action-btn-delete"]="actionBtnDelete"
    ["btn-remove"]="btnRemove"
    ["badge-primary"]="badgePrimary"
    ["badge-success"]="badgeSuccess"
    ["badge-warning"]="badgeWarning"
    ["org-badge"]="orgBadge"
    ["small-text"]="smallText"
    ["settings-section-title"]="settingsSectionTitle"
    ["specialty-container"]="specialtyContainer"
    ["volunteer-type-container"]="volunteerTypeContainer"
    ["collapsible-input"]="collapsibleInput"
    ["specialty-list"]="specialtyList"
    ["volunteer-type-list"]="volunteerTypeList"
    ["flex-row"]="flexRow"
    ["flex-column"]="flexColumn"
    ["margin-top-5"]="marginTop5"
    ["margin-top-10"]="marginTop10"
    ["margin-top-15"]="marginTop15"
    ["margin-top-20"]="marginTop20"
    ["margin-top-30"]="marginTop30"
    ["margin-bottom-5"]="marginBottom5"
    ["margin-bottom-10"]="marginBottom10"
    ["margin-bottom-15"]="marginBottom15"
    ["margin-bottom-20"]="marginBottom20"
    ["margin-bottom-30"]="marginBottom30"
    ["full-width"]="fullWidth"
)

file="index.html"
for kebab in "${!conversions[@]}"; do
    camel="${conversions[$kebab]}"
    # Replace in class attributes
    sed -i.bak "s/class=\"\([^\"]*\)$kebab\([^\"]*\)\"/class=\"\1$camel\2\"/g" "$file"
    sed -i.bak "s/class=\"\([^\"]*\) $kebab\( \|$\)/class=\"\1 $camel\2/g" "$file"
    # Replace in CSS selectors
    sed -i.bak "s/\.$kebab\b/\.$camel/g" "$file"
    # Replace in selectors with pseudo-elements
    sed -i.bak "s/\.$kebab:/\.$camel:/g" "$file"
    sed -i.bak "s/\.$kebab\./\.$camel\./g" "$file"
    sed -i.bak "s/\.$kebab \.\/$kebab /\.$camel \.\/$camel /g" "$file"
done

rm index.html.bak* 2>/dev/null
echo "Conversion complete!"
