CREATE TABLE SITE_INVENTORY (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(255),
  PRICE DOUBLE
);

CREATE TABLE WAREHOUSE_INVENTORY (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(255),
  PRICE DOUBLE
);

INSERT INTO SITE_INVENTORY(NAME, PRICE)
VALUES('Item 1', 100);

INSERT INTO SITE_INVENTORY(NAME, PRICE)
VALUES('Item 2', 200);

INSERT INTO SITE_INVENTORY(NAME, PRICE)
VALUES('Item 3', 300);

INSERT INTO WAREHOUSE_INVENTORY(NAME, PRICE)
VALUES('Item 4', 400);

INSERT INTO WAREHOUSE_INVENTORY(NAME, PRICE)
VALUES('Item 5', 500);

INSERT INTO WAREHOUSE_INVENTORY(NAME, PRICE)
VALUES('Item 6', 600);
