-- USERS
INSERT INTO SC_USER(ID, USER_NAME, USER_PASSWORD)
VALUES (100, 'sheraz', '{noop}password');

INSERT INTO SC_USER(ID, USER_NAME, USER_PASSWORD)
VALUES (110, 'tariq', '{noop}password');

INSERT INTO SC_USER(ID, USER_NAME, USER_PASSWORD)
VALUES (120, 'chaudhry', '{noop}password');

-- ROLES & AUTHORITIES
INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1000, 'ROLE_USER');

INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1010, 'ROLE_ADMIN');

INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1020, 'READ');

INSERT INTO SC_ROLE(ID, ROLE_NAME)
VALUES (1030, 'WRITE');

-- USER and ROLES & AUTHORITIES mapping
-- sheraz - ROLE_ADMIN ROLE_USER READ WRITE
INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2010, 100, 1000);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2020, 100, 1010);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2030, 100, 1020);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2040, 100, 1030);

-- tariq ROLE_USER READ WRITE
INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2050, 110, 1000);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2060, 110, 1020);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2070, 110, 1030);

-- chaudhry - ROLE_USER READ
INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2080, 120, 1000);

INSERT INTO SC_USER_ROLE(ID, SC_USER_ID, SC_ROLE_ID)
VALUES (2090, 120, 1020);
