CREATE TABLE SC_USER
(
    ID            INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_NAME     VARCHAR2,
    USER_PASSWORD VARCHAR2
);

CREATE TABLE SC_ROLE
(
    ID        INTEGER PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR2
);

CREATE TABLE SC_USER_ROLE
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    SC_USER_ID INTEGER,
    SC_ROLE_ID INTEGER,
    CONSTRAINT FK_SC_USER_SC_USER_ROLE FOREIGN KEY (SC_USER_ID) REFERENCES SC_USER (ID),
    CONSTRAINT FK_SC_ROLE_SC_USER_ROLE FOREIGN KEY (SC_ROLE_ID) REFERENCES SC_ROLE (ID)
);
