source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'ios14_cocoapod_alamofire_afnetwork' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios14_cocoapod_alamofire_afnetwork
  pod 'Alamofire', '~> 3.4'
end
