DROP SEQUENCE ID_SEQUENCE;

CREATE SEQUENCE ID_SEQUENCE 
START WITH 10000000 INCREMENT BY 2;

DROP TABLE ATTENDEE;

CREATE TABLE ATTENDEE
(ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
PHONE_NUMBER VARCHAR(20),
ADDRESS_LINE_1 VARCHAR(250),
ADDRESS_LINE_2 VARCHAR(250),
CITY VARCHAR(200),
STATE VARCHAR(100),
ZIP_CODE VARCHAR(20),
DML_DATE TIMESTAMP);

SELECT * FROM ATTENDEE;
